CREATE TABLE Library.Book (
   ISBN VARCHAR( 20 ) NOT NULL ,
   Title VARCHAR( 10 ) NOT NULL ,
   AuthorID SMALLINT( 10 ) NOT NULL ,
   Publisher VARCHAR(20) NOT NULL ,
   PublishDate VARCHAR( 20 ) NOT NULL ,
   Price SMALLINT(10) NOT NULL,
   PRIMARY KEY ( ISBN )
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Library.Author(
	AuthorID SMALLINT(10) NOT NULL ,
	Name VARCHAR(30) NOT NULL ,
	Age VARCHAR(4) NOT NULL ,
	Country VARCHAR(30) NOT NULL ,
	PRIMARY KEY (AuthorID) 
) ENGINE = InnoDB DEFAULT CHARSET=utf8;
